version: '3.9'

services:
  nats:
    image: nats
    ports:
      - 4222
  jaeger:
    image: jaegertracing/all-in-one
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - 5775/udp
      - 6831/udp
      - 6832/udp
      - 5778
      - 16686:16686
      - 14268
      - 9411
  server:
    build:
      args:
        - DIR=server
    ports:
      - 8080:8080
  subscriber:
    build:
      args:
        - DIR=sub
  last:
    build:
      args:
        - DIR=last
    ports:
      - 8090:8080
